global class PartnerPortalCourseCertficate
{
	public PartnerPortalCourseCertficate() 
	{
	}
   
	public String Notes {get; set;}
	public Integer Status {get; set;}
	public String StatusDisplay {get; set;}
    public String StudentName {get; set;}
    public String Title {get; set;}
    public String Uri {get; set;}
    public string certificateId {get; set;}
    public Integer learningPathId {get; set;}
    public string courseId {get; set;}
	public Integer lessonId {get; set;}
    public DateTime expires {get; set;}
	public string studentsId {get; set;}
	public DateTime valid {get; set;}

}