@isTest 
public class UpdatesOpportunityContactRoleTest {
    @isTest
    public static void testMethodOne() {
        Account testAcct = new Account();
        testAcct.Name = 'Test Account';
        testAcct.Type = 'Prospect';
        insert testAcct;
        
        Contact testCon = new Contact();
        testCon.LastName = 'Test';
        testCon.email = 'test@example.com';
        testCon.phone = '1231231232';
        testCon.LeadSource = 'Inbound Call';
        testCon.Accountid = testAcct.Id;
        insert testCon;
        
        Opportunity testOpp = new Opportunity();
        testOpp.Name = 'Test Opportunity';
        testOpp.Accountid = testAcct.Id;
        testOpp.Type = 'New Business';
        testOpp.CloseDate = System.Today() + 30;
        testOpp.StageName = 'New';
        insert testOpp;
        
        OpportunityContactRole testCR = new OpportunityContactRole();
        testCR.Contactid = testCon.Id;
        testCR.Opportunityid = testOpp.Id;
        insert testCR;
        
        update testOpp;
    } 
}